//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Analitika_magacinske_kartice
    {
        public decimal Id_Analitika_magacinske_kartice { get; set; }
        public decimal Id_Robna_kartica { get; set; }
        public decimal Redni_broj_Analitika_magacinske_kartice { get; set; }
        public string Vrsta_prometa_Analitika_magacinske_kartice { get; set; }
        public string Smer_Analitika_magacinske_kartice { get; set; }
        public decimal Kolicina_Analitika_magacinske_kartice { get; set; }
        public decimal Cena_Analitika_magacinske_kartice { get; set; }
        public decimal Vrednost_Analitika_magacinske_kartice { get; set; }
    
        public virtual Robna_kartica Robna_kartica { get; set; }
    }
}
