//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupa_roba
    {
        public Grupa_roba()
        {
            this.Robas = new HashSet<Roba>();
        }
    
        public decimal Id_Grupa_roba { get; set; }
        public decimal Id_PDV { get; set; }
        public decimal Id_Preduzece { get; set; }
        public string Naziv_Grupa_roba { get; set; }
    
        public virtual PDV PDV { get; set; }
        public virtual Preduzece Preduzece { get; set; }
        public virtual ICollection<Roba> Robas { get; set; }
    }
}
