//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jedinica_mere
    {
        public Jedinica_mere()
        {
            this.Robas = new HashSet<Roba>();
        }
    
        public decimal Id_Jedinica_mere { get; set; }
        public string Naziv_Jedinica_mere { get; set; }
        public string Oznaka_Jedinica_mere { get; set; }
    
        public virtual ICollection<Roba> Robas { get; set; }
    }
}
