//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesto
    {
        public Mesto()
        {
            this.Magacins = new HashSet<Magacin>();
            this.Poslovni_partner = new HashSet<Poslovni_partner>();
            this.Preduzeces = new HashSet<Preduzece>();
        }
    
        public decimal Id { get; set; }
        public string Naziv_Mesto { get; set; }
        public string Postansk__broj_Mesto { get; set; }
    
        public virtual ICollection<Magacin> Magacins { get; set; }
        public virtual ICollection<Poslovni_partner> Poslovni_partner { get; set; }
        public virtual ICollection<Preduzece> Preduzeces { get; set; }
    }
}
