//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDV
    {
        public PDV()
        {
            this.Grupa_roba = new HashSet<Grupa_roba>();
            this.Stopa_PDV_a = new HashSet<Stopa_PDV_a>();
        }
    
        public decimal Id_PDV { get; set; }
        public string Naziv_PDV { get; set; }
    
        public virtual ICollection<Grupa_roba> Grupa_roba { get; set; }
        public virtual ICollection<Stopa_PDV_a> Stopa_PDV_a { get; set; }
    }
}
