//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Poslovna : DbContext
    {
        public Poslovna()
            : base("name=Poslovna")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Analitika_magacinske_kartice> Analitika_magacinske_kartice { get; set; }
        public virtual DbSet<Faktura> Fakturas { get; set; }
        public virtual DbSet<Grupa_roba> Grupa_roba { get; set; }
        public virtual DbSet<Jedinica_mere> Jedinica_mere { get; set; }
        public virtual DbSet<Magacin> Magacins { get; set; }
        public virtual DbSet<Mesto> Mestoes { get; set; }
        public virtual DbSet<PDV> PDVs { get; set; }
        public virtual DbSet<Poslovna_godina> Poslovna_godina { get; set; }
        public virtual DbSet<Poslovni_partner> Poslovni_partner { get; set; }
        public virtual DbSet<Preduzece> Preduzeces { get; set; }
        public virtual DbSet<Prijemni_dokument> Prijemni_dokument { get; set; }
        public virtual DbSet<Roba> Robas { get; set; }
        public virtual DbSet<Robna_kartica> Robna_kartica { get; set; }
        public virtual DbSet<Stavka_dokumenta> Stavka_dokumenta { get; set; }
        public virtual DbSet<Stopa_PDV_a> Stopa_PDV_a { get; set; }
    }
}
