//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poslovna_godina
    {
        public Poslovna_godina()
        {
            this.Fakturas = new HashSet<Faktura>();
            this.Robna_kartica = new HashSet<Robna_kartica>();
        }
    
        public decimal Id_Poslovna_godina { get; set; }
        public decimal Id_Preduzece { get; set; }
        public decimal Godina_Poslovna_godina { get; set; }
        public bool Zakljucena_Poslovna_godina { get; set; }
    
        public virtual ICollection<Faktura> Fakturas { get; set; }
        public virtual Preduzece Preduzece { get; set; }
        public virtual ICollection<Robna_kartica> Robna_kartica { get; set; }
    }
}
