//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PoslovnaEntities : DbContext
    {
        public PoslovnaEntities()
            : base("name=PoslovnaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Analitika_magacinske_kartice> Analitika_magacinske_kartice { get; set; }
        public DbSet<Faktura> Fakturas { get; set; }
        public DbSet<Grupa_roba> Grupa_roba { get; set; }
        public DbSet<Jedinica_mere> Jedinica_mere { get; set; }
        public DbSet<Magacin> Magacins { get; set; }
        public DbSet<Mesto> Mestoes { get; set; }
        public DbSet<PDV> PDVs { get; set; }
        public DbSet<Poslovna_godina> Poslovna_godina { get; set; }
        public DbSet<Poslovni_partner> Poslovni_partner { get; set; }
        public DbSet<Preduzece> Preduzeces { get; set; }
        public DbSet<Prijemni_dokument> Prijemni_dokument { get; set; }
        public DbSet<Roba> Robas { get; set; }
        public DbSet<Robna_kartica> Robna_kartica { get; set; }
        public DbSet<Stavka_dokumenta> Stavka_dokumenta { get; set; }
        public DbSet<Stopa_PDV_a> Stopa_PDV_a { get; set; }
    }
}
