//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PoslovnaEntities : DbContext
    {
        public PoslovnaEntities()
            : base("name=PoslovnaEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Analitika_magacinske_kartice> Analitika_magacinske_kartice { get; set; }
        public virtual DbSet<Faktura> Fakturas { get; set; }
        public virtual DbSet<Grupa_roba> Grupa_roba { get; set; }
        public virtual DbSet<Jedinica_mere> Jedinica_mere { get; set; }
        public virtual DbSet<Korisnik> Korisniks { get; set; }
        public virtual DbSet<Magacin> Magacins { get; set; }
        public virtual DbSet<Mesto> Mestoes { get; set; }
        public virtual DbSet<PDV> PDVs { get; set; }
        public virtual DbSet<Poslovna_godina> Poslovna_godina { get; set; }
        public virtual DbSet<Poslovni_partner> Poslovni_partner { get; set; }
        public virtual DbSet<Preduzece> Preduzeces { get; set; }
        public virtual DbSet<Prijemni_dokument> Prijemni_dokument { get; set; }
        public virtual DbSet<Roba> Robas { get; set; }
        public virtual DbSet<Robna_kartica> Robna_kartica { get; set; }
        public virtual DbSet<Stavka_dokumenta> Stavka_dokumenta { get; set; }
        public virtual DbSet<Stopa_PDV_a> Stopa_PDV_a { get; set; }
    
        public virtual int Iskalkulisi(Nullable<decimal> id_PD)
        {
            var id_PDParameter = id_PD.HasValue ?
                new ObjectParameter("Id_PD", id_PD) :
                new ObjectParameter("Id_PD", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Iskalkulisi", id_PDParameter);
        }
    
        public virtual int Proknjizi(Nullable<decimal> id_primke, Nullable<bool> storno)
        {
            var id_primkeParameter = id_primke.HasValue ?
                new ObjectParameter("id_primke", id_primke) :
                new ObjectParameter("id_primke", typeof(decimal));
    
            var stornoParameter = storno.HasValue ?
                new ObjectParameter("storno", storno) :
                new ObjectParameter("storno", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proknjizi", id_primkeParameter, stornoParameter);
        }
    }
}
