//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roba
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Roba()
        {
            this.Robna_kartica = new HashSet<Robna_kartica>();
            this.Stavka_dokumenta = new HashSet<Stavka_dokumenta>();
        }
    
        public decimal Id_Roba { get; set; }
        public decimal Id_Grupa_roba { get; set; }
        public decimal Id_Preduzece { get; set; }
        public decimal Id_Jedinica_mere { get; set; }
        public string Naziv_Roba { get; set; }
    
        public virtual Grupa_roba Grupa_roba { get; set; }
        public virtual Jedinica_mere Jedinica_mere { get; set; }
        public virtual Preduzece Preduzece { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Robna_kartica> Robna_kartica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stavka_dokumenta> Stavka_dokumenta { get; set; }
    }
}
