//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Robna_kartica
    {
        public Robna_kartica()
        {
            this.Analitika_magacinske_kartice = new HashSet<Analitika_magacinske_kartice>();
        }
    
        public decimal Id_Robna_kartica { get; set; }
        public decimal Id_Poslovna_godina { get; set; }
        public decimal Id_Magacin { get; set; }
        public decimal Id_Roba { get; set; }
        public decimal Prosecna_cena_Robna_kartica { get; set; }
        public decimal Poc_stanje_kol_Robna_kartica { get; set; }
        public decimal Poc_stanje_vrednost_Robna_kartica { get; set; }
        public Nullable<decimal> Promet_ulaza_kol_Robna_kartica { get; set; }
        public Nullable<decimal> Promet_ulaza_vr_Robna_kartica { get; set; }
        public Nullable<decimal> Promet_izlaza_kol_Robna_kartica { get; set; }
        public Nullable<decimal> Promet_izlaza_vr_Robna_kartica { get; set; }
        public Nullable<decimal> Ukupna_kolicina_Robna_kartica { get; set; }
        public Nullable<decimal> Ukupna_vrednost_Robna_kartica { get; set; }
    
        public virtual ICollection<Analitika_magacinske_kartice> Analitika_magacinske_kartice { get; set; }
        public virtual Magacin Magacin { get; set; }
        public virtual Poslovna_godina Poslovna_godina { get; set; }
        public virtual Roba Roba { get; set; }
    }
}
