//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stavka_dokumenta
    {
        public decimal Id_Stavka_dokumenta { get; set; }
        public decimal Id_Roba { get; set; }
        public decimal Id_Prijemni_dokument { get; set; }
        public decimal Kolicina_Stavka_dokumenta { get; set; }
        public decimal Nabavna_vrednost_Stavka_dokumenta { get; set; }
        public decimal Procenat_marze_Stavka_dokumenta { get; set; }
        public Nullable<decimal> Transportni_trosak_Stavka_dokumenta { get; set; }
        public Nullable<decimal> Zavisni_trosak_Stavka_dokumenta { get; set; }
        public Nullable<decimal> Kalkulisana_cena_Stavka_dokumenta { get; set; }
        public Nullable<decimal> Ukupna_vrednost_Stavka_dokumenta { get; set; }
    
        public virtual Prijemni_dokument Prijemni_dokument { get; set; }
        public virtual Roba Roba { get; set; }
    }
}
