//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stopa_PDV_a
    {
        public decimal Id_Stopa_PDV_a { get; set; }
        public decimal Id_PDV { get; set; }
        public decimal Stopa_Stopa_PDV_a { get; set; }
        public System.DateTime Datum_vazenja_Stopa_PDV_a { get; set; }
    
        public virtual PDV PDV { get; set; }
    }
}
